---
# tasks file for nfsserver

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install pacakges
  package:
    name: "{{ nfsserver_packages }}"

- name: configure exports
  template:
    src: exports.j2
    dest: /etc/exports
    mode: "0644"
  notify:
    - reload exports

- name: start nfs server
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ nfsserver_services }}"
  when:
    - ansible_connection != "docker"
