---
- name: converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-nfsserver
      nfsserver_exports:
        - share: /home/nfsshare
          hosts:
            - name: 10.0.0.0/24
              options:
                - ro
                - no_subtree_check
                - nohide
            - name: 172.16.0.0/24
              options:
                - rw
                - sync
                - no_wdelay
