---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: check exports
      command: showmounts --exports
      register: nfsserver_check_exports
      failed_when:
        - "'/home' not in nfsserver_check_exports.stdout"
